maxRecentLogLines: 20
alert:
  slack:
    webhook: https://hooks.slack.com/services/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
  pagerduty:
    integrationKey: 898f77d2832d4604c0c1a178f476a5c7
  discord:
    webhook: ''

